### ISSUE TITLE
Can not download the model and data

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [davidstutz/daml-shape-completion#1]
I can not open all of the 'https://s3.eu-central-1.amazonaws.com/avg-shape-completion/xxx' links, so I cannot download the model and datasets. I was wondering if the links are not available now?

Could you please provide me with another way to download?  Thanks !

**Comment by davidstutz** [comment]
Sorry for the late reply. I'll try to make them available from another server. As the files are pretty large, this may take some time.

**Comment by davidstutz** [comment]
See the available links below:


* KITTI (2.7GB): [Amazon AWS](https://s3.eu-central-1.amazonaws.com/avg-shape-completion/cvpr2018_shape_completion_kitti.zip) [MPI-INF](https://datasets.d2.mpi-inf.mpg.de/cvpr2018-shape-completion/cvpr2018_shape_completion_kitti.zip)
* SN-clean (5.7GB): [Amazon AWS](https://s3.eu-central-1.amazonaws.com/avg-shape-completion/cvpr2018_shape_completion_clean.zip) [MPI-INF](https://datasets.d2.mpi-inf.mpg.de/cvpr2018-shape-completion/cvpr2018_shape_completion_clean.zip)
* SN-noisy (4.0GB): [Amazon AWS](https://s3.eu-central-1.amazonaws.com/avg-shape-completion/cvpr2018_shape_completion_noisy.zip) [MPI-INF](https://datasets.d2.mpi-inf.mpg.de/cvpr2018-shape-completion/cvpr2018_shape_completion_noisy.zip)
* Simplified ShapeNet Cars (38.5MB): [Amazon AWS](https://s3.eu-central-1.amazonaws.com/avg-shape-completion/cvpr2018_shape_completion_shapenet_models.zip) [MPI-INF](https://datasets.d2.mpi-inf.mpg.de/cvpr2018-shape-completion/cvpr2018_shape_completion_shapenet_models.zip)

**Comment by SkyeFromKindergarten** [comment]
Thanks for your reply ~





--

郭 燕
厦门大学 信息科学与技术学院
智能科学系 2014级本科生
联系方式：18805926283

At 2018-11-30 22:40:21, "David Stutz" <notifications@github.com> wrote:


See the available links below:

KITTI (2.7GB): Amazon AWSMPI-INF
SN-clean (5.7GB): Amazon AWSMPI-INF
SN-noisy (4.0GB): Amazon AWSMPI-INF
Simplified ShapeNet Cars (38.5MB): Amazon AWSMPI-INF
